fix: VaultService.List will now get ALL records, not just the first p…
topicuskeyhub/go-keyhub pull request #10
Opened 2022-06-09 14:25 UTC by maikelpoot

VaultService.List will now get ALL records, not just the first page (100 records)

This is implemented by a Range Objects which uses a default of 100 records per page.

```
searchRange := model.NewRange()
for ok := true; ok; ok = searchRange.NextPage() {
		response, err := s.sling.New().****.Add(searchRange.GetRequestRangeHeader()).Add(searchRange.GetRequestModeHeader()).Receive(results, errorReport)
		searchRange.ParseResponse(response)
}
```

- **searchRange.NextPage()** Will check if there are more pages (Based on current end and total)
- **searchRange.ParseResponse(response)** Will parse the response header 'Content-Range' and update the current range and total.

The Request headers can be set by using these in the sling add function:
- **searchRange.GetRequestRangeHeader()** Gives the "Range: items 0-99" header values
- **searchRange.GetRequestModeHeader()** Gives the "topicus-Range-Count: Exact" header values

2022-06-09 14:43 UTC, hielkehoeve commented
Fetching all records instead of using paging is bad practice. I understand this might be required for some situations like terraform, but this should not be default behaviour for a SDK.

The SDK should make it easy to paginate through the results, but not return all vault records by default.

2022-06-09 14:46 UTC, hielkehoeve requested changes
I suggest we provide an API which allows for pagination such that software using our SDK can decide when en how to paginate.

2022-06-09 14:57 UTC, maikelpoot commented
I don't agree. 
a. The SDK has two function for getting all records it should get all records:
```golang
//GetRecords Retrieve all vault records for a group including audit (secrets are not included)
func (s *VaultService) GetRecords(g *model.Group) (result []model.VaultRecord, err error) 

//List Retrieve all vault records for a group (secrets are not included, default audit = true)
func (s *VaultService) List(group *model.Group, query *model.VaultRecordQueryParams, additional *model.VaultRecordAdditionalQueryParams) (records []model.VaultRecord, err error) 
```
So only retrieving page one is a bug.

b. I don't thing you should burden the "user" with the sdk with api limitations as paging, and offer at least a "getAll" feature. 
In the end, getALL functions will get build, so why not implement it in de SDK.

2022-06-09 15:03 UTC, hielkehoeve commented
A. Retrieving one page is indeed a bug. This needs to be fixed. But now we have 2 methods retrieving ALL while I am certain not every client wants to always retreive ALL records.
B. Pagination is not an API limitation, it is part of the API. It prevents long requests and large response bodies.

Having some methods which can help you retreive a page AND having a get all method is the way to go.

2022-06-10 04:09 UTC, maikelpoot commented
A. And thats why this is (just) a fix PR. Fixing the bug that the SDK doesn't do what it says "Retrieve all vault records for a group"

For B there should be a feature request resulting with a feat PR and is out of scope of this PR.
i all ready placed the Range functionality in a seperate model, so in the future it can be used in more places by the SDK or Application.

And besides, this is a SDK, not an API.

2022-06-10 06:36 UTC, hielkehoeve commented
👍

2022-06-10 06:36 UTC, hielkehoeve approved these changes

2022-06-10 07:24 UTC, merged